use_frameworks!

target 'Almanakka_Example' do
  pod 'Almanakka', :path => '../'

  target 'Almanakka_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
